_deploy: &deploy
  provider: releases
  api_key:
    secure: EhcrhFPVqt0hiRqHDex0HsQrII04LXPTMIOykzVY65Kx0JBPzqE6zjDhKyKNal9BiU7ssUvQuk2MGSJUPkusb1QZitOFb/b8niXIEG0OgakqLYekr+OIctYWh9adqdzN2M91dhTbZgAFPF0n+6YNb041J4PbJodb2v9SFMCwoJrzskYCH0LzGr0Y71J9b3/qUR6W30QaGvBX3BJPR1jz36Jh44SShYwnRUwCMvsDPQxEaw/ERfM0Ug/IgQmuUFwf34yvRyyBPQHeyLykLWIZx2Egw27hQq6IqSL6tjKm8O12q6R9u8M3nMJew1+DCt18SKK065MDHKIITMctF324xlMq8DzmMmkZZOhi83Tgc/n44cL4MO4OmpNUMGczgPfLCoUof+COXpDcTT22q+6pC1I0QIb0WTDaAyD0afynhUMiJD+Zc1x80ick5Bj/SVK377QQPFG+P6it4P9Rrs/NePFZhrvOolN1+5sKiXGpyzJC/ndSXn1RlJdFhqmWBEMsVF+QUtOE+5WrTqm5FQHydBl6B6pT3KNoxWLsipbH2SLCjdRRxS00lOYUEfTEN0EN1aSX9k0BX6OAx2cxHhNYmfgMaDAcIE1bHzCfAPw0W3oqtEVJA2fAVPyxK3BiND6kp4xVfd6sYaaTWpTigGVsu8kDb25c14yHhC0PQ6Nmcfg=
  file: XmSeedtable-${TRAVIS_OS_NAME}.zip
  skip_cleanup: true
  on:
    tags: true
_after_success: &after_success
  - cp -R seedtable-x11/XmSeedtable/bin/Release XmSeedtable
  - zip -r -9 XmSeedtable-${TRAVIS_OS_NAME}.zip XmSeedtable
_script_with_test: &script_with_test
  - xbuild /p:Configuration=Release seedtable.sln
  - mono ./packages/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./seedtable-test/bin/Release/seedtable-test.dll -verbose
language: csharp
mono: latest
solution: seedtable-x11/XmSeedtable.sln
matrix:
  include:
    - script: *script_with_test
    - script: *script_with_test
      os: osx
    - install:
        - sudo apt-get -qq update
        - sudo apt-get -qq install libmotif-dev libxmu-dev libxt-dev
        - nuget restore seedtable.sln
        - nuget restore seedtable-x11/XmSeedtable.sln
      after_success: *after_success
      deploy: *deploy
    - env:
        # - XQUARTZ_VERSION=2.7.8
        - PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig
      os: osx
      osx_image: xcode7.3
      install:
        # - curl -L -O http://xquartz.macosforge.org/downloads/SL/XQuartz-${XQUARTZ_VERSION}.dmg
        # - hdiutil mount XQuartz-${XQUARTZ_VERSION}.dmg
        # - sudo installer -store -pkg /Volumes/XQuartz-${XQUARTZ_VERSION}/XQuartz.pkg -target /
        # - hdiutil unmount /Volumes/XQuartz-${XQUARTZ_VERSION}
        - brew update
        - brew install openmotif
        - nuget restore seedtable.sln
        - nuget restore seedtable-x11/XmSeedtable.sln
      after_success: *after_success
      deploy: *deploy
