language: csharp
mono: none
dotnet: 3.1.100
solution: seedtable-x11/XmSeedtable.sln
os: osx
osx_image: xcode11.2
matrix:
  include:
    - script:
        - dotnet restore seedtable-test
        - dotnet test seedtable-test
    - script:
        - dotnet tool install ElectronNET.CLI -g
        - npm install -g electron-builder
        - cd seedtable-egui
        - electronize build /target osx
      deploy:
        provider: releases
        api_key:
          secure: EhcrhFPVqt0hiRqHDex0HsQrII04LXPTMIOykzVY65Kx0JBPzqE6zjDhKyKNal9BiU7ssUvQuk2MGSJUPkusb1QZitOFb/b8niXIEG0OgakqLYekr+OIctYWh9adqdzN2M91dhTbZgAFPF0n+6YNb041J4PbJodb2v9SFMCwoJrzskYCH0LzGr0Y71J9b3/qUR6W30QaGvBX3BJPR1jz36Jh44SShYwnRUwCMvsDPQxEaw/ERfM0Ug/IgQmuUFwf34yvRyyBPQHeyLykLWIZx2Egw27hQq6IqSL6tjKm8O12q6R9u8M3nMJew1+DCt18SKK065MDHKIITMctF324xlMq8DzmMmkZZOhi83Tgc/n44cL4MO4OmpNUMGczgPfLCoUof+COXpDcTT22q+6pC1I0QIb0WTDaAyD0afynhUMiJD+Zc1x80ick5Bj/SVK377QQPFG+P6it4P9Rrs/NePFZhrvOolN1+5sKiXGpyzJC/ndSXn1RlJdFhqmWBEMsVF+QUtOE+5WrTqm5FQHydBl6B6pT3KNoxWLsipbH2SLCjdRRxS00lOYUEfTEN0EN1aSX9k0BX6OAx2cxHhNYmfgMaDAcIE1bHzCfAPw0W3oqtEVJA2fAVPyxK3BiND6kp4xVfd6sYaaTWpTigGVsu8kDb25c14yHhC0PQ6Nmcfg=
        file: seedtable-egui/bin/Desktop/*.*
        file_glob: true
        skip_cleanup: true
        on:
          tags: true
    - env:
        # - XQUARTZ_VERSION=2.7.8
        - PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig
      install:
        # - curl -L -O http://xquartz.macosforge.org/downloads/SL/XQuartz-${XQUARTZ_VERSION}.dmg
        # - hdiutil mount XQuartz-${XQUARTZ_VERSION}.dmg
        # - sudo installer -store -pkg /Volumes/XQuartz-${XQUARTZ_VERSION}/XQuartz.pkg -target /
        # - hdiutil unmount /Volumes/XQuartz-${XQUARTZ_VERSION}
        - brew update
        - brew install openmotif
        - dotnet restore seedtable
        - dotnet restore seedtable-x11/XmSeedtable
      script:
        - sh publish-xm-osx.sh
        - sh releases-xm-osx.sh
      deploy:
        provider: releases
        api_key:
          secure: EhcrhFPVqt0hiRqHDex0HsQrII04LXPTMIOykzVY65Kx0JBPzqE6zjDhKyKNal9BiU7ssUvQuk2MGSJUPkusb1QZitOFb/b8niXIEG0OgakqLYekr+OIctYWh9adqdzN2M91dhTbZgAFPF0n+6YNb041J4PbJodb2v9SFMCwoJrzskYCH0LzGr0Y71J9b3/qUR6W30QaGvBX3BJPR1jz36Jh44SShYwnRUwCMvsDPQxEaw/ERfM0Ug/IgQmuUFwf34yvRyyBPQHeyLykLWIZx2Egw27hQq6IqSL6tjKm8O12q6R9u8M3nMJew1+DCt18SKK065MDHKIITMctF324xlMq8DzmMmkZZOhi83Tgc/n44cL4MO4OmpNUMGczgPfLCoUof+COXpDcTT22q+6pC1I0QIb0WTDaAyD0afynhUMiJD+Zc1x80ick5Bj/SVK377QQPFG+P6it4P9Rrs/NePFZhrvOolN1+5sKiXGpyzJC/ndSXn1RlJdFhqmWBEMsVF+QUtOE+5WrTqm5FQHydBl6B6pT3KNoxWLsipbH2SLCjdRRxS00lOYUEfTEN0EN1aSX9k0BX6OAx2cxHhNYmfgMaDAcIE1bHzCfAPw0W3oqtEVJA2fAVPyxK3BiND6kp4xVfd6sYaaTWpTigGVsu8kDb25c14yHhC0PQ6Nmcfg=
        file: releases/XmSeedtable-osx.zip
        skip_cleanup: true
        on:
          tags: true
