version: "{build}"
image: Visual Studio 2019
branches:
  except:
    - gh-pages
platform:
  - Any CPU
configuration:
  - Release
before_build:
  - dotnet restore
build_script:
  - .\publish.bat
  - .\releases.ps1
test_script:
  - dotnet test
artifacts:
  - path: releases/seedtable.zip
    name: seedtable
  - path: releases/seedtable-linux.zip
    name: seedtable-linux
  - path: releases/seedtable-osx.zip
    name: seedtable-osx
  - path: releases/seedtable-need-runtime.zip
    name: seedtable-need-runtime
  - path: releases/seedtable-gui.zip
    name: seedtable-gui
  - path: releases/seedtable-gui-need-runtime.zip
    name: seedtable-gui-need-runtime
deploy:
  provider: GitHub
  auth_token:
    secure: sf2zcb1xd8VNZCqJF/VYLFGjDphmkBFXrjoFoviFndPkIJ6zj/LPPzG1c63yowsC
  draft: false
  prerelease: false
  artifact: /releases\/seedtable*\.zip/
  on:
    appveyor_repo_tag: true
