version: "{build}"
image: Visual Studio 2019
branches:
  except:
    - gh-pages
platform:
  - Any CPU
configuration:
  - Release
before_build:
  - nuget restore
build:
  project: seedtable.sln
test:
  assemblies:
    only:
      - "**/*-test.dll"
artifacts:
  - path: seedtable-gui/bin/Release
    name: seedtable
deploy:
  provider: GitHub
  auth_token:
    secure: sf2zcb1xd8VNZCqJF/VYLFGjDphmkBFXrjoFoviFndPkIJ6zj/LPPzG1c63yowsC
  draft: false
  prerelease: false
  artifact: seedtable-gui/bin/seedtable.zip
  on:
    appveyor_repo_tag: true
