version: "{build}"
image: Visual Studio 2019
branches:
  except:
    - gh-pages
platform:
  - Any CPU
configuration:
  - Release
before_build:
  - dotnet restore
  - dotnet tool install ElectronNET.CLI -g
  - npm install -g electron-builder
build_script:
  - .\publish.bat
  - ps: .\releases.ps1
  - .\publish_egui.bat
  - ps: .\releases-egui.ps1
test_script:
  - dotnet test
artifacts:
  - path: releases/seedtable.zip
    name: seedtable
  - path: releases/seedtable-linux.zip
    name: seedtable-linux
  - path: releases/seedtable-osx.zip
    name: seedtable-osx
  - path: releases/seedtable-need-runtime.zip
    name: seedtable-need-runtime
  - path: releases/seedtable-gui.zip
    name: seedtable-gui
  - path: releases/seedtable-gui-need-runtime.zip
    name: seedtable-gui-need-runtime
  - path: releases/seedtable-egui-win.zip
    name: seedtable-egui-win
deploy:
  provider: GitHub
  auth_token:
    secure: pXNt94D78LGVsrWyPtoaFzXZI1rUt8iCaEvjjhQnM1hwyH/eV1Vnh/WhJQ9eLmgR
  draft: false
  prerelease: false
  artifact: /releases\/seedtable.*\.zip/
  on:
    appveyor_repo_tag: true
